### ISSUE TITLE
Cannot run script with suricata 5.0.0

### ISSUE THREAD

**Issue by noobfromvn** [B0fH/yara-suricata#2]
I got this errror when using your script with suricata 5.0.0:

`bad argument #3 to 'format' (string expected, got boolean)`

It's working fine in suricata 4.1+

**Comment by noobfromvn** [comment]
Seem suricata 5.0.0 has a small change in SCFileInfo:

`fileid, txid, name, size, magic, md5 = SCFileInfo()`

**Comment by B0fH** [comment]
Hello -
 The script still works for me using the latest Suricata master [Suricata version 5.0.0-dev (64a789bbf 2019-10-18)]. What does your filestore configuration look like in suricata.yaml?

Thanks,
 Elazar
